// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBeXKpxTf4zQ2omFJREmsPQn0J4H2YTFc',
    appId: '1:438661247426:web:692a128f0cdb256c41e65b',
    messagingSenderId: '438661247426',
    projectId: 'zagelgp',
    authDomain: 'zagelgp.firebaseapp.com',
    storageBucket: 'zagelgp.appspot.com',
    measurementId: 'G-2NLWRZBTMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3YJEb0wttCB_DzYxgS2jE5FxS_VQ_W_o',
    appId: '1:438661247426:android:6ea9a9b9ab44638041e65b',
    messagingSenderId: '438661247426',
    projectId: 'zagelgp',
    storageBucket: 'zagelgp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTISmNO5Rn--i9LCYseVbGull667HtoMA',
    appId: '1:438661247426:ios:e5774d39143872e341e65b',
    messagingSenderId: '438661247426',
    projectId: 'zagelgp',
    storageBucket: 'zagelgp.appspot.com',
    iosBundleId: 'com.example.zagel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTISmNO5Rn--i9LCYseVbGull667HtoMA',
    appId: '1:438661247426:ios:afe42aba7357f30741e65b',
    messagingSenderId: '438661247426',
    projectId: 'zagelgp',
    storageBucket: 'zagelgp.appspot.com',
    iosBundleId: 'com.example.zagel.RunnerTests',
  );
}
